name: Automated Tests

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  test_php:
    name: Test PHP
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['5.6', '7.3']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set PHP version
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
    - name: PHP version
      run: php --version
    - name: Install dependencies
      run: composer install --ignore-platform-reqs
    - name: Run PHPCS
      run: ./vendor/bin/phpcs --standard=WordPress *.php inc/*.php
